# -*- mode: ruby -*-
# vi: set ft=ruby :

# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
ADDITIONALFILES = Dir.pwd + "/AdditionalFiles"


Vagrant.configure("2") do |config|

  config.vm.synced_folder ADDITIONALFILES, "/var/www"
  config.vm.box = "ubuntu/bionic64"

 # Configure the Webserver
  config.vm.define "web" do |web|
    web.vm.provider :virtualbox do |vb|
     vb.name = "m300_webserver"
     vb.memory = 1024
    end

 # network configuration
  web.vm.network "private_network", ip: "192.168.0.20"
 #   virtualbox_intnet: true
  web.vm.network "forwarded_port", guest: 80, host: 18706
  
 # install webserver
  web.vm.provision "shell", path: "web_shell.sh"


  end

 # Configure the Database
  config.vm.define "db" do |db|
    db.vm.provider :virtualbox do |vb|
      vb_db.name = "m300_database"
     vb_db.memory = 1024
  end

 # network configuration
  db.vm.network "private_network", ip: "192.168.0.30"
 #   virtualbox_intnet: true
  db.vm.network "forwarded_port", guest: 3306, host: 33306

 # install database
 db.vm.provision "shell", path: "db_shell.sh"
 

  end


end

